name: Build MATLAB PREP Artifacts via CI

on: [push]


jobs:
  build:
    name: Build MATLAB PREP Artifacts
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Download MATLAB packages and test data
      run: python config/pipeline_setup.py

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v0
      with:
        release: latest

    - name: Run MATLAB PREP
      uses: matlab-actions/run-command@v0
      with:
        command: "warning('off');run('generate_artifacts.m');exit;"

    - name: Upload PREP artifacts
      uses: actions/upload-artifact@v2
      with:
        name: matprep-artifacts
        path: artifacts/*
