name: Build MATLAB PREP Artifacts via CI

on: [push]


jobs:
  build:
    name: Build MATLAB PREP Artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Download MATLAB packages and test data
      run: python helpers/pipeline_setup.py

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v0
      with:
        release: R2020a

    - name: Run MATLAB PREP
      uses: matlab-actions/run-command@v0
      with:
        command: generate_artifacts

    - name: Upload PREP artifacts
      with:
        name: matprep-artifacts
        path: artifacts/
