name: Build MATLAB PREP Artifacts via CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 4 1 * *"

jobs:
  build:
    name: Build MATLAB PREP Artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Download MATLAB packages and test data
      run: python config/pipeline_setup.py

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: latest
        products: Signal_Processing_Toolbox Statistics_and_Machine_Learning_Toolbox

    - name: Run MATLAB PREP
      uses: matlab-actions/run-command@v2
      with:
        command: "warning('off');run('generate_artifacts.m');exit;"

    - name: Upload PREP artifacts
      uses: actions/upload-artifact@v4
      with:
        name: matprep-artifacts
        path: artifacts/*
        include-hidden-files: true
        overwrite: true

    - name: Upload PREP artifacts to GitHub Releases on tag
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
